@BookQuotes.Api_HostAddress = http://localhost:5047

GET {{BookQuotes.Api_HostAddress}}/health
Accept: application/json

###

GET {{BookQuotes.Api_HostAddress}}/openapi/v1.json
Accept: application/json

###

GET {{BookQuotes.Api_HostAddress}}/api/books
Accept: application/json

###

POST {{BookQuotes.Api_HostAddress}}/api/books
Content-Type: application/json

{
  "title": "Refactoring",
  "author": "Martin Fowler",
  "publishedDate": "2018-11-19"
}

###

POST {{BookQuotes.Api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "userName": "demo-user",
  "password": "BookQuotes1",
  "confirmPassword": "BookQuotes1"
}

###

POST {{BookQuotes.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "userName": "demo-user",
  "password": "BookQuotes1"
}

###
